### ISSUE TITLE
Error when runing the development server

### ISSUE THREAD

**Issue by ouafaGit** [idbakkasse/helium#93]
**Describe the bug**
When I start the theme `npm run serve` it gives me the following error:

`Error: Error: spawn shopify ENOENT`

This is the full output:

> helium@2.0.0 serve C:\laragon\www\shopify\vanrycke
> helium serve
 >Info:  Helium is Serving files
 >Warning:  Helium is waiting for theme upload to finish
 >Info:  Helium is watching over your changes
 >**Error:  Error: spawn shopify ENOENT**
 >Warning:  Helium command finished

**Environement**
Windows 10
Node 14.16.1
npm 6.14.12

**To Reproduce**
run `npm run serve`
See error

**Expected behavior**
The shop should be served on the 9292 port

**Comment by idbakkasse** [comment]
Hey there, Please try to upgrade to node 17 and rerun the command.

**Comment by ouafaGit** [comment]
Hello @idbakkasse 

I did upgrade to node version 17 but I still have the same issue.

**Comment by idbakkasse** [comment]
Hey, that's weird did you try to run `npm run watch` then open a new terminal session on the same folder and run `shopify theme serve`

**Comment by idbakkasse** [comment]
I think that something to do with Windows, thats weird since I used on mac no issues, the commande in it's core it's juste `npm watch` and `shopify serve` combined in one shell process session.
